#!/usr/bin/env bash
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "ERROR: run as root (sudo)."
  exit 1
fi

if [[ $# -lt 1 ]]; then
  echo "Usage: sudo $0 <peer-manifest-url-or-file> [--force]"
  exit 1
fi

MANIFEST_SOURCE="$1"
FORCE_RESTART="${2:-}"

CONFIG_DIR="/opt/zugchain/config"
MANIFEST_LOCAL="${CONFIG_DIR}/peer-manifest.json"
OUT_ENV="${CONFIG_DIR}/dynamic-peers.env"
PENDING_FILE="${CONFIG_DIR}/.peer_refresh_pending"
LAST_RESTART_FILE="${CONFIG_DIR}/.last_peer_restart_ts"
LOCK_FILE="/var/lock/zugchain-peer-refresh.lock"
MIN_RESTART_INTERVAL_SEC="${MIN_RESTART_INTERVAL_SEC:-900}"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "ERROR: required command not found: $1"
    exit 1
  fi
}

need_cmd jq
need_cmd flock

mkdir -p "${CONFIG_DIR}"
touch "${LOCK_FILE}"
exec 9>"${LOCK_FILE}"
if ! flock -n 9; then
  echo "[INFO] Peer refresh already running; skipping."
  exit 0
fi

TMP_MANIFEST="$(mktemp /tmp/zug-peer-manifest.XXXXXX.json)"
cleanup() {
  rm -f "${TMP_MANIFEST}"
}
trap cleanup EXIT

if [[ "${MANIFEST_SOURCE}" =~ ^https?:// ]]; then
  need_cmd curl
  curl -fsSL "${MANIFEST_SOURCE}" -o "${TMP_MANIFEST}"
else
  if [[ ! -f "${MANIFEST_SOURCE}" ]]; then
    echo "ERROR: source manifest not found: ${MANIFEST_SOURCE}"
    exit 1
  fi
  cp -f "${MANIFEST_SOURCE}" "${TMP_MANIFEST}"
fi

GETH_BOOTNODES="$(jq -r '.geth_bootnodes // [] | join(",")' "${TMP_MANIFEST}")"
PRYSM_BOOTSTRAP_NODES="$(jq -r '.prysm_bootstrap_nodes // [] | join(",")' "${TMP_MANIFEST}")"
STATIC_ENODES="$(jq -r '.static_peers // [] | join(",")' "${TMP_MANIFEST}")"
UPDATED_AT="$(jq -r '.updated_at // ""' "${TMP_MANIFEST}")"

OLD_GETH_BOOTNODES=""
OLD_PRYSM_BOOTSTRAP_NODES=""
OLD_STATIC_ENODES=""
if [[ -f "${OUT_ENV}" ]]; then
  OLD_GETH_BOOTNODES="$(sed -n 's/^GETH_BOOTNODES="\(.*\)"$/\1/p' "${OUT_ENV}" | head -n 1)"
  OLD_PRYSM_BOOTSTRAP_NODES="$(sed -n 's/^PRYSM_BOOTSTRAP_NODES="\(.*\)"$/\1/p' "${OUT_ENV}" | head -n 1)"
  OLD_STATIC_ENODES="$(sed -n 's/^STATIC_ENODES="\(.*\)"$/\1/p' "${OUT_ENV}" | head -n 1)"
fi

PEER_CHANGED=0
if [[ "${GETH_BOOTNODES}" != "${OLD_GETH_BOOTNODES}" ]] || \
   [[ "${PRYSM_BOOTSTRAP_NODES}" != "${OLD_PRYSM_BOOTSTRAP_NODES}" ]] || \
   [[ "${STATIC_ENODES}" != "${OLD_STATIC_ENODES}" ]]; then
  PEER_CHANGED=1
fi

# Keep latest manifest copy for observability/runbooks.
cp -f "${TMP_MANIFEST}" "${MANIFEST_LOCAL}"
chmod 644 "${MANIFEST_LOCAL}"

cat > "${OUT_ENV}" <<EOF
# Generated by 05_refresh_peers_and_restart.sh
MANIFEST_SOURCE="${MANIFEST_SOURCE}"
MANIFEST_UPDATED_AT="${UPDATED_AT}"
GETH_BOOTNODES="${GETH_BOOTNODES}"
PRYSM_BOOTSTRAP_NODES="${PRYSM_BOOTSTRAP_NODES}"
STATIC_ENODES="${STATIC_ENODES}"
EOF
chmod 640 "${OUT_ENV}"

if [[ "${PEER_CHANGED}" -eq 1 ]]; then
  date +%s > "${PENDING_FILE}"
  echo "[INFO] Peer list changed, pending restart flagged."
fi

if [[ "${PEER_CHANGED}" -eq 0 && ! -f "${PENDING_FILE}" && "${FORCE_RESTART}" != "--force" ]]; then
  echo "[INFO] No peer change detected."
  exit 0
fi

is_el_syncing() {
  local ipc="/opt/zugchain/data/geth/geth.ipc"
  if [[ ! -S "${ipc}" ]] || ! command -v geth >/dev/null 2>&1; then
    echo "unknown"
    return
  fi
  local out
  out="$(geth attach "${ipc}" --exec "eth.syncing" 2>/dev/null | tr -d '[:space:]' || true)"
  if [[ "${out}" == "false" ]]; then
    echo "false"
  elif [[ "${out}" == \{* ]]; then
    echo "true"
  else
    echo "unknown"
  fi
}

is_cl_syncing() {
  if ! command -v curl >/dev/null 2>&1; then
    echo "unknown"
    return
  fi
  local out
  out="$(curl -fsS --max-time 3 http://127.0.0.1:3500/eth/v1/node/syncing 2>/dev/null || true)"
  if [[ -z "${out}" ]]; then
    echo "unknown"
    return
  fi
  local syncing
  syncing="$(echo "${out}" | jq -r '.data.is_syncing // "unknown"' 2>/dev/null || echo "unknown")"
  if [[ "${syncing}" == "true" ]]; then
    echo "true"
  elif [[ "${syncing}" == "false" ]]; then
    echo "false"
  else
    echo "unknown"
  fi
}

if [[ "${FORCE_RESTART}" != "--force" ]]; then
  NOW_TS="$(date +%s)"
  LAST_TS="0"
  if [[ -f "${LAST_RESTART_FILE}" ]]; then
    LAST_TS="$(cat "${LAST_RESTART_FILE}" 2>/dev/null || echo "0")"
  fi
  if [[ "${LAST_TS}" =~ ^[0-9]+$ ]]; then
    AGE="$((NOW_TS - LAST_TS))"
    if (( AGE < MIN_RESTART_INTERVAL_SEC )); then
      echo "[WARN] Restart throttled (${AGE}s < ${MIN_RESTART_INTERVAL_SEC}s)."
      echo "[WARN] Pending peer update kept for next run."
      exit 0
    fi
  fi

  EL_SYNCING="$(is_el_syncing)"
  CL_SYNCING="$(is_cl_syncing)"
  if [[ "${EL_SYNCING}" == "true" || "${CL_SYNCING}" == "true" ]]; then
    echo "[WARN] Node is syncing (EL=${EL_SYNCING}, CL=${CL_SYNCING}); delaying restart."
    echo "[WARN] Pending peer update kept for next run."
    exit 0
  fi
fi

echo "[INFO] Restarting zugchain-geth and zugchain-beacon..."
systemctl restart zugchain-geth
sleep 5
systemctl restart zugchain-beacon

date +%s > "${LAST_RESTART_FILE}"
rm -f "${PENDING_FILE}"

echo "[OK] Peer config refreshed and services restarted."
